# Generated by Django 2.2.5 on 2019-10-01 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('content', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Stock',
        ),
    ]
