# Generated by Django 2.2.5 on 2019-10-01 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_auto_20191001_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockitem',
            name='slug',
            field=models.SlugField(default='default-slug'),
            preserve_default=False,
        ),
    ]
