# Generated by Django 2.2.5 on 2019-10-07 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_auto_20191001_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockitem',
            name='title',
            field=models.CharField(max_length=120),
        ),
    ]
