# Generated by Django 2.2.6 on 2019-11-13 08:06

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('blog', '0011_auto_20191112_1814'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StockItem',
            new_name='Stock',
        ),
    ]
