# Generated by Django 2.2.5 on 2019-11-14 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20191113_1306'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='selling_field',
            new_name='selling_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='title',
        ),
    ]
