# Generated by Django 2.2.5 on 2019-11-14 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20191114_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealproduct',
            name='count',
            field=models.IntegerField(),
        ),
    ]
