# Generated by Django 2.2.5 on 2019-11-01 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('surname', models.CharField(max_length=120)),
                ('patronymic', models.CharField(max_length=120)),
                ('company_name', models.CharField(max_length=120)),
            ],
            options={
                'ordering': ['-pk'],
            },
        ),
    ]
