# Generated by Django 2.2.5 on 2019-10-01 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_stockitem_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockitem',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
