# Generated by Django 2.2.5 on 2019-10-14 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0006_stockitem_contractor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stockitem',
            options={'ordering': ['-pk']},
        ),
    ]
