# Generated by Django 2.2.6 on 2019-10-15 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0007_auto_20191014_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockitem',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='image/'),
        ),
    ]
